#!/bin/bash
set -e
if [[ $EUID -ne 0 ]];then
        echo "[!] Must be run as Root"
        exit 1
fi
echo -------------------------------------------------------------------
echo ‎‎‎‎‎‎‎‎‎‎'                       'UPDATING PACKAGES
echo -------------------------------------------------------------------
apt update
echo -------------------------------------------------------------------
echo ‎‎‎‎'                      'INSTALLING PYTHON3
echo -------------------------------------------------------------------
apt --assume-yes install python3
echo -------------------------------------------------------------------
echo ‎‎‎‎'                         'INSTALLING PIP
echo -------------------------------------------------------------------
apt --assume-yes install python3-pip
echo -------------------------------------------------------------------
echo ‎‎‎‎'                       'INSTALLING APACHE
echo -------------------------------------------------------------------
apt --assume-yes install apache2
apt --assume-yes install php php-cli php-fpm php-json php-common php-mysql php-zip php-gd php-mbstring php-curl php-xml php-pear php-bcmath
echo -------------------------------------------------------------------
echo ‎‎‎‎'                        'INSTALLING MYSQL
echo -------------------------------------------------------------------
apt --assume-yes install mysql-server
echo [+] Installing required python modules...
sleep 1
python3 -m pip install mysql-connector-python
pip3 install -r requirements.txt
echo [+] Done
