#!/bin/bash
echo -------------------------------------------------------------------
echo ‎‎‎‎‎‎‎‎‎‎'                       'SETTING UP APACHE
echo -------------------------------------------------------------------
cp services/apache/bootstrap_shop.conf /etc/apache2/sites-available
cp -r services/apache/bootstrap_shop /var/www/
cp services/apache/hosts /etc/
a2dissite 000-default.conf
a2ensite bootstrap_shop.conf
systemctl reload apache2
echo [*] Website url : http://bootstrap-shop.com

